// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using topg.Web.Data;

#nullable disable

namespace topg.Web.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20260512110259_AddAnswersToQuestions")]
    partial class AddAnswersToQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnswerType")
                        .HasColumnType("integer");

                    b.Property<long?>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Questions");

                    b.HasDiscriminator<int>("QuestionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.QuizTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.ImageQuestion", b =>
                {
                    b.HasBaseType("topg.Web.Templating.DomainObjects.Question");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.SoundQuestion", b =>
                {
                    b.HasBaseType("topg.Web.Templating.DomainObjects.Question");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.TextQuestion", b =>
                {
                    b.HasBaseType("topg.Web.Templating.DomainObjects.Question");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.Board", b =>
                {
                    b.HasOne("topg.Web.Templating.DomainObjects.QuizTemplate", "Template")
                        .WithMany("Boards")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.Question", b =>
                {
                    b.HasOne("topg.Web.Templating.DomainObjects.Board", null)
                        .WithMany("Questions")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.Board", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("topg.Web.Templating.DomainObjects.QuizTemplate", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
