-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Boards"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "TemplateId" bigint NOT NULL,
    "Order" integer NOT NULL,
    CONSTRAINT "PK_Boards" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS public."Questions"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "QuestionType" integer NOT NULL,
    "AnswerType" integer NOT NULL,
    "Points" integer NOT NULL,
    "Category" text COLLATE pg_catalog."default" NOT NULL,
    "QuestionText" text COLLATE pg_catalog."default",
    "BoardId" bigint,
    "CorrectAnswer" text COLLATE pg_catalog."default" DEFAULT ''::text,
    "ImageUri" text COLLATE pg_catalog."default",
    "TextQuestion_CorrectAnswer" text COLLATE pg_catalog."default",
    "TextQuestion_QuestionText" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Templates"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Templates" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Boards"
    ADD CONSTRAINT "FK_Boards_Templates_TemplateId" FOREIGN KEY ("TemplateId")
    REFERENCES public."Templates" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Boards_TemplateId"
    ON public."Boards"("TemplateId");


ALTER TABLE IF EXISTS public."Questions"
    ADD CONSTRAINT "FK_Questions_Boards_BoardId" FOREIGN KEY ("BoardId")
    REFERENCES public."Boards" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Questions_BoardId"
    ON public."Questions"("BoardId");

END;